// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "provider": string;
      "apiBase": string;
      "model": string;
      "apiKey": string;
      "contextMaxPromptTokens": string;
      "contextRecentTurns": string;
    };
  }
}
